version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - gnuboard_db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mysql

   gnuboard:
     depends_on:
       - db
     image: csh8130/gnuboard:latest
     volumes:
       - gnuboard_files:/var/www
     ports:
       - "80:80"
     restart: always
volumes:
     gnuboard_db:
     gnuboard_files:
