version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - $PWD/docker_volume/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mysql

   gnuboard:
     depends_on:
       - db
     image: csh8130/gnuboard:latest
     ports:
       - "80:80"
     restart: always
